
import type { Role } from '@/types/securities/securities.types';

export const mockRoles: Role[] = [
  {
    id: 1,
    name: 'Super Admin',
    description: 'Full access to all organization modules',
    roleType: 'SUPER_ADMIN',
    userCount: 2,
    permissionCount: 48,
    status: 'ACTIVE',
    createdAt: '2026-08-01',
    updatedAt: '2026-08-01',
  },
  {
    id: 2,
    name: 'Administrator',
    description: 'Administrative access to organization operations',
    roleType: 'ADMIN',
    userCount: 5,
    permissionCount: 39,
    status: 'ACTIVE',
    createdAt: '2026-08-02',
    updatedAt: '2026-08-02',
  },
  {
    id: 3,
    name: 'Finance Manager',
    description: 'Manages finance and accounting operations',
    roleType: 'MANAGER',
    userCount: 14,
    permissionCount: 21,
    status: 'ACTIVE',
    createdAt: '2026-08-03',
    updatedAt: '2026-08-01',
  },
  {
    id: 4,
    name: 'Inventory Manager',
    description: 'Manages inventory and warehouse operations',
    roleType: 'MANAGER',
    userCount: 8,
    permissionCount: 18,
    status: 'ACTIVE',
    createdAt: '2026-08-03',
    updatedAt: '2026-08-03',
  },
  {
    id: 5,
    name: 'Standard User',
    description: 'Basic operational access',
    roleType: 'STANDARD',
    userCount: 90,
    permissionCount: 8,
    status: 'ACTIVE',
    createdAt: '2026-08-04',
    updatedAt: '2026-08-01',
  },
];