$kind: http-request
name: http://localhost:5000/api/organization/org-group/3
url: http://localhost:5000/api/organization/org-group/3
method: PATCH
body:
  type: json
  content: "{\r

    \  \"shortName\": \"RSI Updated\",\r

    \  \"email\": \"admin.updated@retailshopindia.com\",\r

    \  \"phoneNumber\": \"9998887776\",\r

    \  \"status\": \"ACTIVE\"\r

    }"
auth:
  type: bearer
  credentials:
    token: "{{authToken}}"
order: 5000
