import {
  Package,
  CheckCircle2,
  XCircle,
  Tag,
  Warehouse,
  MapPin,
  Wallet,
  Boxes,
  Bookmark,
  ClipboardCheck,
  AlertTriangle,
  PackageX,
  Clock,
  Truck,
  Move,
  RefreshCw,
  Target,
  TrendingUp,
  Zap,
  Sparkles,
  LayoutGrid,
  ScanBarcode,
  PackageOpen,
  Shuffle,
  SlidersHorizontal,
  FileText,
  Download,
  Printer,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { KpiTone } from '@/types/inventoryDashboard'

export const KPI_ICONS: Record<string, LucideIcon> = {
  package: Package,
  check: CheckCircle2,
  x: XCircle,
  tag: Tag,
  warehouse: Warehouse,
  mapPin: MapPin,
  wallet: Wallet,
  boxes: Boxes,
  bookmark: Bookmark,
  clipboardCheck: ClipboardCheck,
  alertTriangle: AlertTriangle,
  packageX: PackageX,
  clock: Clock,
  xCircle: XCircle,
  truck: Truck,
  move: Move,
  refresh: RefreshCw,
  target: Target,
  trendingUp: TrendingUp,
  zap: Zap,
  sparkle: Sparkles,
  layoutGrid: LayoutGrid,
  scan: ScanBarcode,
  packageOpen: PackageOpen,
  shuffle: Shuffle,
  sliders: SlidersHorizontal,
  fileText: FileText,
  download: Download,
  printer: Printer,
}

/** Icon chip background/text colors per KPI tone (matches the design's pastel chips). */
export const TONE_STYLES: Record<KpiTone, { chip: string; icon: string }> = {
  blue: { chip: 'bg-[#EFF6FF]', icon: 'text-[#155DFC]' },
  green: { chip: 'bg-[#ECFDF5]', icon: 'text-[#009966]' },
  red: { chip: 'bg-[#FEF2F2]', icon: 'text-[#E7000B]' },
  purple: { chip: 'bg-[#F5F3FF]', icon: 'text-[#8E4EC6]' },
  orange: { chip: 'bg-[#FFF7ED]', icon: 'text-[#F54900]' },
  amber: { chip: 'bg-[#FFFBEB]', icon: 'text-[#E17100]' },
  teal: { chip: 'bg-[#F0FDFA]', icon: 'text-[#0D9488]' },
}
